export const JOIN_OPTION_INVALID = 3000
export const ALREADY_JOINED = 3001
export const NO_REMAINING_SLOT = 3002
export const ERROR_SET_VISITOR_USERDATA = 3003
export const ERROR_CREATE_ENTITY = 3004
export const ERROR_UPDATE_ENTITY = 3005
export const ERROR_REMOVE_ENTITY = 3006
