repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern', '^(?!((feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-zA-Z0-9\-]+)$).*']
  - repo: https://github.com/jorisroovers/gitlint
    rev: 'v0.17.0'
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.21.0'
    hooks:
      - id: eslint
        stages: [commit]
