"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_STATE_CAM_MIC = exports.UPDATE_STATE_CAM_MIC = exports.WEBRTC_RESUME_STREAM = exports.WEBRTC_PAUSE_STREAM = exports.WEBRTC_PUBLISHER_CLOSED = exports.WEBRTC_NEW_PUBLISHER = exports.WEBRTC_ICE_UPDATE = exports.WEBRTC_SDP_ANSWER = exports.WEBRTC_SDP_OFFER = exports.WEBRTC_SUBSCRIBE = exports.WEBRTC_PUBLISH = void 0;
exports.WEBRTC_PUBLISH = 'WEBRTC_PUBLISH';
exports.WEBRTC_SUBSCRIBE = 'WEBRTC_SUBSCRIBE';
exports.WEBRTC_SDP_OFFER = 'WEBRTC_SDP_OFFER';
exports.WEBRTC_SDP_ANSWER = 'WEBRTC_SDP_ANSWER';
exports.WEBRTC_ICE_UPDATE = 'WEBRTC_ICE_UPDATE';
exports.WEBRTC_NEW_PUBLISHER = 'WEBRTC_NEW_PUBLISHER';
exports.WEBRTC_PUBLISHER_CLOSED = 'WEBRTC_PUBLISHER_CLOSED';
exports.WEBRTC_PAUSE_STREAM = 'WEBRTC_PAUSE_STREAM';
exports.WEBRTC_RESUME_STREAM = 'WEBRTC_RESUME_STREAM';
exports.UPDATE_STATE_CAM_MIC = 'UPDATE_STATE_CAM_MIC';
exports.GET_STATE_CAM_MIC = 'GET_STATE_CAM_MIC';
//# sourceMappingURL=constants.js.map