export enum Topic {
  NOTIFICATION = "NOTIFICATION",
  API_CALL = "API_CALL"
}

export enum MessageType {
  ROOM_CREATE = 'ROOM_CREATE',
  ROOM_UPDATE = 'ROOM_UPDATE',
  ROOM_REMOVE = 'ROOM_REMOVE',
}