export const WEBRTC_PUBLISH = 'WEBRTC_PUBLISH'
export const WEBRTC_SUBSCRIBE = 'WEBRTC_SUBSCRIBE'

export const WEBRTC_SDP_OFFER = 'WEBRTC_SDP_OFFER'
export const WEBRTC_SDP_ANSWER = 'WEBRTC_SDP_ANSWER'
export const WEBRTC_ICE_UPDATE = 'WEBRTC_ICE_UPDATE'

export const WEBRTC_NEW_PUBLISHER = 'WEBRTC_NEW_PUBLISHER'
export const WEBRTC_PUBLISHER_CLOSED = 'WEBRTC_PUBLISHER_CLOSED'

export const WEBRTC_PAUSE_STREAM = 'WEBRTC_PAUSE_STREAM'
export const WEBRTC_RESUME_STREAM = 'WEBRTC_RESUME_STREAM'

export const UPDATE_STATE_CAM_MIC = 'UPDATE_STATE_CAM_MIC'
export const GET_STATE_CAM_MIC = 'GET_STATE_CAM_MIC'
